export const countries = [
    {
        order: 1,
        customerCode: 'Brazil',
        service_area: 8515767,
        service_quality: 0.85,
        service_total: 0.15,
        electric_startNumber: 205809000,
        electric_endNumber: 0.054,
        electric_quality: 0.274,
        electric_total: 0.672,
        water_startNumber: 2353025,
        water_endNumber: 0,
        water_quality: 0,
        water_total: 0,
        vehicle_car: 0,
        vehicle_motorbike: 0,
        vehicle_bike: 0,
        vehicle_electricBike: 0,
        vehicle_electricMotorbike: 0,
        vehicle_total: 0,
        total: 0,
    },
    {
        order: 2,
        customerCode: 'HP',
        service_area: 8515767,
        service_quality: 0.85,
        service_total: 0.15,
        electric_startNumber: 205809000,
        electric_endNumber: 0.054,
        electric_quality: 0.274,
        electric_total: 0.672,
        water_startNumber: 2353025,
        water_endNumber: 0,
        water_quality: 0,
        water_total: 0,
        vehicle_car: 0,
        vehicle_motorbike: 0,
        vehicle_bike: 0,
        vehicle_electricBike: 0,
        vehicle_electricMotorbike: 0,
        vehicle_total: 0,
        total: 0,
    },
    {
        order: 3,
        customerCode: 'VN',
        service_area: 8515767,
        service_quality: 0.85,
        service_total: 0.15,
        electric_startNumber: 205809000,
        electric_endNumber: 0.054,
        electric_quality: 0.274,
        electric_total: 0.672,
        water_startNumber: 2353025,
        water_endNumber: 0,
        water_quality: 0,
        water_total: 0,
        vehicle_car: 0,
        vehicle_motorbike: 0,
        vehicle_bike: 0,
        vehicle_electricBike: 0,
        vehicle_electricMotorbike: 0,
        vehicle_total: 0,
        total: 0,
    },
    {
        order: 4,
        customerCode: 'ABC',
        service_area: 8515767,
        service_quality: 0.85,
        service_total: 0.15,
        electric_startNumber: 205809000,
        electric_endNumber: 0.054,
        electric_quality: 0.274,
        electric_total: 0.672,
        water_startNumber: 2353025,
        water_endNumber: 0,
        water_quality: 0,
        water_total: 0,
        vehicle_car: 0,
        vehicle_motorbike: 0,
        vehicle_bike: 0,
        vehicle_electricBike: 0,
        vehicle_electricMotorbike: 0,
        vehicle_total: 0,
        total: 0,
    },
];
