export const CREATE_ACCOUNT_REQUESTED = 'app/LtAccount/CREATE_ACCOUNT_REQUESTED';
export const CREATE_ACCOUNT_REQUESTED_SUCCEEDED = 'app/LtAccount/CREATE_ACCOUNT_REQUESTED_SUCCEEDED';
export const CREATE_ACCOUNT_REQUESTED_FAILED = 'app/LtAccount/CREATE_ACCOUNT_REQUESTED_FAILED';

export const UPDATE_ACCOUNT_REQUESTED = 'app/LtAccount/UPDATE_ACCOUNT_REQUESTED';
export const UPDATE_ACCOUNT_REQUESTED_SUCCEEDED = 'app/LtAccount/UPDATE_ACCOUNT_REQUESTED_SUCCEEDED';
export const UPDATE_ACCOUNT_REQUESTED_FAILED = 'app/LtAccount/UPDATE_ACCOUNT_REQUESTED_FAILED';

export const UPDATE_PASSWORD_REQUESTED = 'app/LtAccount/UPDATE_PASSWORD_REQUESTED';
export const UPDATE_PASSWORD_REQUESTED_SUCCEEDED = 'app/LtAccount/UPDATE_PASSWORD_REQUESTED_SUCCEEDED';
export const UPDATE_PASSWORD_REQUESTED_FAILED = 'app/LtAccount/UPDATE_PASSWORD_REQUESTED_FAILED';

export const RESET_ACCOUNT = 'app/LtAccount/RESET_ACCOUNT';
export const FECTH_ACCOUNT='app/LtAccount/FECTH_ACCOUNT';
export const FECTH_ACCOUNT_SUCCESS='app/LtAccount/FECTH_ACCOUNT_SUCCESS';
export const FECTH_ACCOUNT_FAILER='app/LtAccount/FECTH_ACCOUNT_FAILER';

export const MERGE_DATA = 'app/LtAccount/MERGE_DATA';
