version: '2'
services:

  # The Application
  web-mipec-01:
    container_name: web-mipec-01
    restart: always
    build:
      context: ./
      dockerfile: web.dockerfile
    working_dir: /var/www
    networks:
      - traefik_traefik
      - default
    # volumes:
    #   - ./:/var/www
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web-mipec.entrypoints=http"
      - "traefik.http.routers.web-mipec.rule=Host(`quanlytoanha.lifetek.vn`)"
      - "traefik.docker.network=traefik_traefik"
      - "traefik.http.services.web-mipec.loadbalancer.server.port=80"
    
      - "traefik.http.middlewares.cweb-mipec-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.web-mipec.middlewares=web-mipec-https-redirect"
      - "traefik.http.routers.web-mipec-secure.rule=Host(`quanlytoanha.lifetek.vn`)"
      - "traefik.http.routers.web-mipec-secure.tls=true"
      - "traefik.http.routers.web-mipec-secure.tls.certresolver=http"

networks:
  traefik_traefik:
    external: true
