/*
 *
 * StockGuaranteePage constants
 *
 */



export const CHANGE_TYPE = 'app/StockGuaranteePage/CHANGE_TYPE';

export const GET_STOCK_GUARANTEE = 'app/StockGuaranteePage/GET_STOCK_GUARANTEE';
export const GET_STOCK_GUARANTEE_SUCCESS = 'app/StockGuaranteePage/GET_STOCK_GUARANTEE_SUCCESS';
export const GET_STOCK_GUARANTEE_FAILURE = 'app/StockGuaranteePage/GET_STOCK_GUARANTEE_FAILURE';

export const CREATE_STOCK_GUARANTEE = 'app/StockGuaranteePage/CREATE_STOCK_GUARANTEE';
export const CREATE_STOCK_GUARANTEE_SUCCESS = 'app/StockGuaranteePage/CREATE_STOCK_GUARANTEE_SUCCESS';
export const CREATE_STOCK_GUARANTEE_FAILURE = 'app/StockGuaranteePage/CREATE_STOCK_GUARANTEE_FAILURE';

export const UPDATE_STOCK_GUARANTEE = 'app/StockGuaranteePage/UPDATE_STOCK_GUARANTEE';
export const UPDATE_STOCK_GUARANTEE_SUCCESS = 'app/StockGuaranteePage/UPDATE_STOCK_GUARANTEE_SUCCESS';
export const UPDATE_STOCK_GUARANTEE_FAILURE = 'app/StockGuaranteePage/UPDATE_STOCK_GUARANTEE_FAILURE';

export const DELETE_STOCK_GUARANTEE = 'app/StockGuaranteePage/DELETE_STOCK_GUARANTEE';
export const DELETE_STOCK_GUARANTEE_SUCCESS = 'app/StockGuaranteePage/DELETE_STOCK_GUARANTEE_SUCCESS';
export const DELETE_STOCK_GUARANTEE_FAILURE = 'app/StockGuaranteePage/DELETE_STOCK_GUARANTEE_FAILURE';

export const GET_STOCK_GUARANTEE_TASK = 'app/StockGuaranteePage/GET_STOCK_GUARANTEE_TASK';
export const GET_STOCK_GUARANTEE_TASK_SUCCESS = 'app/StockGuaranteePage/GET_STOCK_GUARANTEE_TASK_SUCCESS';
export const GET_STOCK_GUARANTEE_TASK_FAILURE = 'app/StockGuaranteePage/GET_STOCK_GUARANTEE_TASK_FAILURE';

export const CREATE_STOCK_GUARANTEE_TASK = 'app/StockGuaranteePage/CREATE_STOCK_GUARANTEE_TASK';
export const CREATE_STOCK_GUARANTEE_TASK_SUCCESS = 'app/StockGuaranteePage/CREATE_STOCK_GUARANTEE_TASK_SUCCESS';
export const CREATE_STOCK_GUARANTEE_TASK_FAILURE = 'app/StockGuaranteePage/CREATE_STOCK_GUARANTEE_TASK_FAILURE';

export const UPDATE_STOCK_GUARANTEE_TASK = 'app/StockGuaranteePage/UPDATE_STOCK_GUARANTEE_TASK';
export const UPDATE_STOCK_GUARANTEE_TASK_SUCCESS = 'app/StockGuaranteePage/UPDATE_STOCK_GUARANTEE_TASK_SUCCESS';
export const UPDATE_STOCK_GUARANTEE_TASK_FAILURE = 'app/StockGuaranteePage/UPDATE_STOCK_GUARANTEE_TASK_FAILURE';

export const DELETE_STOCK_GUARANTEE_TASK = 'app/StockGuaranteePage/DELETE_STOCK_GUARANTEE_TASK';
export const DELETE_STOCK_GUARANTEE_TASK_SUCCESS = 'app/StockGuaranteePage/DELETE_STOCK_GUARANTEE_TASK_SUCCESS';
export const DELETE_STOCK_GUARANTEE_TASK_FAILURE = 'app/StockGuaranteePage/DELETE_STOCK_GUARANTEE_TASK_FAILURE';

//---------------------------------------------------//

export const GET_STOCK_MAINTAINER = 'app/StockGuaranteePage/GET_STOCK_MAINTAINER';
export const GET_STOCK_MAINTAINER_SUCCESS = 'app/StockGuaranteePage/GET_STOCK_MAINTAINER_SUCCESS';
export const GET_STOCK_MAINTAINER_FAILURE = 'app/StockGuaranteePage/GET_STOCK_MAINTAINER_FAILURE';

export const CREATE_STOCK_MAINTAINER = 'app/StockGuaranteePage/CREATE_STOCK_MAINTAINER';
export const CREATE_STOCK_MAINTAINER_SUCCESS = 'app/StockGuaranteePage/CREATE_STOCK_MAINTAINER_SUCCESS';
export const CREATE_STOCK_MAINTAINER_FAILURE = 'app/StockGuaranteePage/CREATE_STOCK_MAINTAINER_FAILURE';

export const UPDATE_STOCK_MAINTAINER = 'app/StockGuaranteePage/UPDATE_STOCK_MAINTAINER';
export const UPDATE_STOCK_MAINTAINER_SUCCESS = 'app/StockGuaranteePage/UPDATE_STOCK_MAINTAINER_SUCCESS';
export const UPDATE_STOCK_MAINTAINER_FAILURE = 'app/StockGuaranteePage/UPDATE_STOCK_MAINTAINER_FAILURE';

export const DELETE_STOCK_MAINTAINER = 'app/StockGuaranteePage/DELETE_STOCK_MAINTAINER';
export const DELETE_STOCK_MAINTAINER_SUCCESS = 'app/StockGuaranteePage/DELETE_STOCK_MAINTAINER_SUCCESS';
export const DELETE_STOCK_MAINTAINER_FAILURE = 'app/StockGuaranteePage/DELETE_STOCK_MAINTAINER_FAILURE';

export const GET_STOCK_MAINTAINER_TASK = 'app/StockGuaranteePage/GET_STOCK_MAINTAINER_TASK';
export const GET_STOCK_MAINTAINER_TASK_SUCCESS = 'app/StockGuaranteePage/GET_STOCK_MAINTAINER_TASK_SUCCESS';
export const GET_STOCK_MAINTAINER_TASK_FAILURE = 'app/StockGuaranteePage/GET_STOCK_MAINTAINER_TASK_FAILURE';

export const CREATE_STOCK_MAINTAINER_TASK = 'app/StockGuaranteePage/CREATE_STOCK_MAINTAINER_TASK';
export const CREATE_STOCK_MAINTAINER_TASK_SUCCESS = 'app/StockGuaranteePage/CREATE_STOCK_MAINTAINER_TASK_SUCCESS';
export const CREATE_STOCK_MAINTAINER_TASK_FAILURE = 'app/StockGuaranteePage/CREATE_STOCK_MAINTAINER_TASK_FAILURE';

export const UPDATE_STOCK_MAINTAINER_TASK = 'app/StockGuaranteePage/UPDATE_STOCK_MAINTAINER_TASK';
export const UPDATE_STOCK_MAINTAINER_TASK_SUCCESS = 'app/StockGuaranteePage/UPDATE_STOCK_MAINTAINER_TASK_SUCCESS';
export const UPDATE_STOCK_MAINTAINER_TASK_FAILURE = 'app/StockGuaranteePage/UPDATE_STOCK_MAINTAINER_TASK_FAILURE';

export const DELETE_STOCK_MAINTAINER_TASK = 'app/StockGuaranteePage/DELETE_STOCK_MAINTAINER_TASK';
export const DELETE_STOCK_MAINTAINER_TASK_SUCCESS = 'app/StockGuaranteePage/DELETE_STOCK_MAINTAINER_TASK_SUCCESS';
export const DELETE_STOCK_MAINTAINER_TASK_FAILURE = 'app/StockGuaranteePage/DELETE_STOCK_MAINTAINER_TASK_FAILURE';

export const CLEANUP = 'app/StockGuaranteePage/CLEANUP';