/*
 *
 * AssetGuaranteePage constants
 *
 */



export const CHANGE_TYPE = 'app/AssetGuaranteePage/CHANGE_TYPE';

export const GET_ASSET_GUARANTEE = 'app/AssetGuaranteePage/GET_ASSET_GUARANTEE';
export const GET_ASSET_GUARANTEE_SUCCESS = 'app/AssetGuaranteePage/GET_ASSET_GUARANTEE_SUCCESS';
export const GET_ASSET_GUARANTEE_FAILURE = 'app/AssetGuaranteePage/GET_ASSET_GUARANTEE_FAILURE';

export const CREATE_ASSET_GUARANTEE = 'app/AssetGuaranteePage/CREATE_ASSET_GUARANTEE';
export const CREATE_ASSET_GUARANTEE_SUCCESS = 'app/AssetGuaranteePage/CREATE_ASSET_GUARANTEE_SUCCESS';
export const CREATE_ASSET_GUARANTEE_FAILURE = 'app/AssetGuaranteePage/CREATE_ASSET_GUARANTEE_FAILURE';

export const UPDATE_ASSET_GUARANTEE = 'app/AssetGuaranteePage/UPDATE_ASSET_GUARANTEE';
export const UPDATE_ASSET_GUARANTEE_SUCCESS = 'app/AssetGuaranteePage/UPDATE_ASSET_GUARANTEE_SUCCESS';
export const UPDATE_ASSET_GUARANTEE_FAILURE = 'app/AssetGuaranteePage/UPDATE_ASSET_GUARANTEE_FAILURE';

export const DELETE_ASSET_GUARANTEE = 'app/AssetGuaranteePage/DELETE_ASSET_GUARANTEE';
export const DELETE_ASSET_GUARANTEE_SUCCESS = 'app/AssetGuaranteePage/DELETE_ASSET_GUARANTEE_SUCCESS';
export const DELETE_ASSET_GUARANTEE_FAILURE = 'app/AssetGuaranteePage/DELETE_ASSET_GUARANTEE_FAILURE';

export const GET_ASSET_GUARANTEE_TASK = 'app/AssetGuaranteePage/GET_ASSET_GUARANTEE_TASK';
export const GET_ASSET_GUARANTEE_TASK_SUCCESS = 'app/AssetGuaranteePage/GET_ASSET_GUARANTEE_TASK_SUCCESS';
export const GET_ASSET_GUARANTEE_TASK_FAILURE = 'app/AssetGuaranteePage/GET_ASSET_GUARANTEE_TASK_FAILURE';

export const CREATE_ASSET_GUARANTEE_TASK = 'app/AssetGuaranteePage/CREATE_ASSET_GUARANTEE_TASK';
export const CREATE_ASSET_GUARANTEE_TASK_SUCCESS = 'app/AssetGuaranteePage/CREATE_ASSET_GUARANTEE_TASK_SUCCESS';
export const CREATE_ASSET_GUARANTEE_TASK_FAILURE = 'app/AssetGuaranteePage/CREATE_ASSET_GUARANTEE_TASK_FAILURE';

export const UPDATE_ASSET_GUARANTEE_TASK = 'app/AssetGuaranteePage/UPDATE_ASSET_GUARANTEE_TASK';
export const UPDATE_ASSET_GUARANTEE_TASK_SUCCESS = 'app/AssetGuaranteePage/UPDATE_ASSET_GUARANTEE_TASK_SUCCESS';
export const UPDATE_ASSET_GUARANTEE_TASK_FAILURE = 'app/AssetGuaranteePage/UPDATE_ASSET_GUARANTEE_TASK_FAILURE';

export const DELETE_ASSET_GUARANTEE_TASK = 'app/AssetGuaranteePage/DELETE_ASSET_GUARANTEE_TASK';
export const DELETE_ASSET_GUARANTEE_TASK_SUCCESS = 'app/AssetGuaranteePage/DELETE_ASSET_GUARANTEE_TASK_SUCCESS';
export const DELETE_ASSET_GUARANTEE_TASK_FAILURE = 'app/AssetGuaranteePage/DELETE_ASSET_GUARANTEE_TASK_FAILURE';

//---------------------------------------------------//

export const GET_ASSET_MAINTAINER = 'app/AssetGuaranteePage/GET_ASSET_MAINTAINER';
export const GET_ASSET_MAINTAINER_SUCCESS = 'app/AssetGuaranteePage/GET_ASSET_MAINTAINER_SUCCESS';
export const GET_ASSET_MAINTAINER_FAILURE = 'app/AssetGuaranteePage/GET_ASSET_MAINTAINER_FAILURE';

export const CREATE_ASSET_MAINTAINER = 'app/AssetGuaranteePage/CREATE_ASSET_MAINTAINER';
export const CREATE_ASSET_MAINTAINER_SUCCESS = 'app/AssetGuaranteePage/CREATE_ASSET_MAINTAINER_SUCCESS';
export const CREATE_ASSET_MAINTAINER_FAILURE = 'app/AssetGuaranteePage/CREATE_ASSET_MAINTAINER_FAILURE';

export const UPDATE_ASSET_MAINTAINER = 'app/AssetGuaranteePage/UPDATE_ASSET_MAINTAINER';
export const UPDATE_ASSET_MAINTAINER_SUCCESS = 'app/AssetGuaranteePage/UPDATE_ASSET_MAINTAINER_SUCCESS';
export const UPDATE_ASSET_MAINTAINER_FAILURE = 'app/AssetGuaranteePage/UPDATE_ASSET_MAINTAINER_FAILURE';

export const DELETE_ASSET_MAINTAINER = 'app/AssetGuaranteePage/DELETE_ASSET_MAINTAINER';
export const DELETE_ASSET_MAINTAINER_SUCCESS = 'app/AssetGuaranteePage/DELETE_ASSET_MAINTAINER_SUCCESS';
export const DELETE_ASSET_MAINTAINER_FAILURE = 'app/AssetGuaranteePage/DELETE_ASSET_MAINTAINER_FAILURE';

export const GET_ASSET_MAINTAINER_TASK = 'app/AssetGuaranteePage/GET_ASSET_MAINTAINER_TASK';
export const GET_ASSET_MAINTAINER_TASK_SUCCESS = 'app/AssetGuaranteePage/GET_ASSET_MAINTAINER_TASK_SUCCESS';
export const GET_ASSET_MAINTAINER_TASK_FAILURE = 'app/AssetGuaranteePage/GET_ASSET_MAINTAINER_TASK_FAILURE';

export const CREATE_ASSET_MAINTAINER_TASK = 'app/AssetGuaranteePage/CREATE_ASSET_MAINTAINER_TASK';
export const CREATE_ASSET_MAINTAINER_TASK_SUCCESS = 'app/AssetGuaranteePage/CREATE_ASSET_MAINTAINER_TASK_SUCCESS';
export const CREATE_ASSET_MAINTAINER_TASK_FAILURE = 'app/AssetGuaranteePage/CREATE_ASSET_MAINTAINER_TASK_FAILURE';

export const UPDATE_ASSET_MAINTAINER_TASK = 'app/AssetGuaranteePage/UPDATE_ASSET_MAINTAINER_TASK';
export const UPDATE_ASSET_MAINTAINER_TASK_SUCCESS = 'app/AssetGuaranteePage/UPDATE_ASSET_MAINTAINER_TASK_SUCCESS';
export const UPDATE_ASSET_MAINTAINER_TASK_FAILURE = 'app/AssetGuaranteePage/UPDATE_ASSET_MAINTAINER_TASK_FAILURE';

export const DELETE_ASSET_MAINTAINER_TASK = 'app/AssetGuaranteePage/DELETE_ASSET_MAINTAINER_TASK';
export const DELETE_ASSET_MAINTAINER_TASK_SUCCESS = 'app/AssetGuaranteePage/DELETE_ASSET_MAINTAINER_TASK_SUCCESS';
export const DELETE_ASSET_MAINTAINER_TASK_FAILURE = 'app/AssetGuaranteePage/DELETE_ASSET_MAINTAINER_TASK_FAILURE';

export const CLEANUP = 'app/AssetGuaranteePage/CLEANUP';